# Generated by Django 5.1.1 on 2024-09-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilSeleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_tes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status_kelulusan', models.CharField(choices=[('Lulus', 'Lulus'), ('Tidak Lulus', 'Tidak Lulus')], default='Tidak Lulus', max_length=20)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tes', models.DateField()),
                ('lokasi_tes', models.CharField(max_length=255)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
    ]
