# Generated by Django 5.1.1 on 2024-10-17 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('jawaban_benar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TesOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_tes', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_siswa', models.CharField(max_length=255)),
                ('benar', models.BooleanField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TesOnline.soaltes')),
            ],
        ),
        migrations.AddField(
            model_name='soaltes',
            name='tes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TesOnline.tesonline'),
        ),
    ]
