# Generated by Django 5.1.1 on 2024-10-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabansiswa',
            name='status_jawaban',
            field=models.CharField(choices=[('Benar', 'Benar'), ('Salah', 'Salah')], default='Salah', max_length=20),
        ),
    ]
