# Generated by Django 5.1.1 on 2024-09-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telepon', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('status_pendaftaran', models.CharField(choices=[('Pending', 'Pending'), ('Terverifikasi', 'Terverifikasi'), ('Ditolak', 'Ditolak')], default='Pending', max_length=20)),
                ('tanggal_pendaftaran', models.DateTimeField(auto_now_add=True)),
                ('verifikasi_dokumen', models.BooleanField(default=False)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='DokumenSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(max_length=255)),
                ('file_dokumen', models.FileField(upload_to='dokumen_siswa/')),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
    ]
