"""
Django settings for pendaftaransiswaberbasisweb project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fdk11cr4+p4d_at8a2zgdxz!%&l3u9h(9oqnfc=^f!!9e3_dv-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pendaftaransiswaberbasisweb',
    'siswa',
    'TesOnline',
    'jadwal_test' ,
    'user' ,
    'django_extensions',
    'pendaftaransiswaberbasisweb_backend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pendaftaransiswaberbasisweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pendaftaransiswaberbasisweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pendaftaransiswaweb',
        'USER': 'postgres',
        'PASSWORD': 'Sandydayak9',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": "Custom suffix in <title> tag",
    "SITE_HEADER": "PENDAFTARAN SISWA SMK BERBASIS WEB",
    # "SITE_SYMBOL": "person",  # symbol from icon set
    "SITE_URL" : "/",
    "SITE_ICON": {
        "light": lambda request: static("assets/logosmk.png"),  # light mode
        "dark": lambda request: static("assets/logosmk.png"),  # dark mode
    },
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Jadwal Test"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Hasil Seleksi"),
                        "icon": "verified",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:jadwal_test_hasilseleksi_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Jadwal Tes"),
                        "icon": "schedule",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:jadwal_test_jadwaltes_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    }
                ],
            },
            {
                "title": _("Siswa"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Program Studi"),
                        "icon": "auto_stories",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:siswa_programstudi_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Siswa"),
                        "icon": "groups",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:siswa_siswa_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    }
                ],
            },
            {
                "title": _("Tes Online"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Jawaban Siswa"),
                        "icon": "download",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:TesOnline_jawabansiswa_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Tes Online"),
                        "icon": "quiz",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:TesOnline_tesonline_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    }
                ],
            },
            {
                "title": _("User"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Log Aktivitas"),
                        "icon": "update",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:user_logaktivitas_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("User"),
                        "icon": "account_circle",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:user_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    }
                ],
            },
        ],
    },
}